In [1]:
import numpy as np

In [2]:
a = np.array([1,3,4])

In [3]:
b = np.array([4,5,6])

In [4]:
c = np.concatenate([a,b])

In [5]:
c

array([1, 3, 4, 4, 5, 6])

## 二维数组

In [6]:
d = np.arange(6).reshape(-1,3)

In [7]:
e = np.arange(9).reshape(-1,3)

In [8]:
f = np.concatenate([e,d])

In [9]:
f


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [10]:
d

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
f = np.arange(2,8).reshape(3,2)

In [14]:
f

array([[2, 3],
       [4, 5],
       [6, 7]])

In [15]:
g = np.concatenate([e,f],axis=1) #axis=0 纵向合并，axis = 1 横向合并

In [16]:
g

array([[0, 1, 2, 2, 3],
       [3, 4, 5, 4, 5],
       [6, 7, 8, 6, 7]])

## 一维和二维合并

In [17]:
h = np.arange(4).reshape(2,2)

In [18]:
i = np.array([22,33])

In [19]:
np.concatenate([h,i])

ValueError: all the input arrays must have same number of dimensions

In [20]:
i.reshape(1,-1)

array([[22, 33]])

In [23]:
np.concatenate([h,i.reshape(1,-1)])

array([[ 0,  1],
       [ 2,  3],
       [22, 33]])

In [24]:
np.vstack([h,i])

array([[ 0,  1],
       [ 2,  3],
       [22, 33]])

In [26]:
np.hstack([h,i.reshape(-1,1)])

array([[ 0,  1, 22],
       [ 2,  3, 33]])

## 数组分割

In [27]:
x = np.arange(10)

In [28]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.split(x,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [30]:
np.split(x,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [32]:
# np.split(x,3)   #ValueError: array split does not result in an equal division


In [36]:
np.split(x,[4,6])  # 4,6是分割点，以此点分割数组

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]

In [39]:
x1,x2,x3 = np.split(x,[2,8])

In [40]:
x2

array([2, 3, 4, 5, 6, 7])

In [42]:
y = np.arange(16).reshape(4,4)

In [43]:
y1,y2 = np.split(y,[2])

In [44]:
y1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [45]:
y2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
y3,y4 = np.split(y,[5],axis=1)

In [51]:
y3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
y4

array([], shape=(4, 0), dtype=int32)

In [53]:
np.vsplit(y,[1])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [54]:
np.hsplit(y,[3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]