In [1]:
import numpy as np

In [2]:
x = np.random.random(100)

In [3]:
x

array([0.89473403, 0.16465403, 0.39983422, 0.04847884, 0.42100679,
       0.29189265, 0.25096484, 0.74338184, 0.3500027 , 0.02564521,
       0.82287963, 0.82407642, 0.22300128, 0.96067355, 0.34980795,
       0.66060892, 0.11798941, 0.94487759, 0.83944144, 0.67267667,
       0.21101069, 0.98896025, 0.17657846, 0.53015449, 0.98888601,
       0.70690799, 0.40022719, 0.35338704, 0.99145635, 0.11364153,
       0.45701346, 0.59131903, 0.82465118, 0.73692643, 0.87914495,
       0.13707913, 0.07256939, 0.46941733, 0.60082907, 0.23557747,
       0.2378213 , 0.36868425, 0.59265994, 0.41355485, 0.11022469,
       0.50615914, 0.34023932, 0.5641136 , 0.72598691, 0.53494108,
       0.6010587 , 0.73559771, 0.90431814, 0.38901312, 0.06464854,
       0.60458392, 0.93590993, 0.49982096, 0.64100495, 0.96185543,
       0.03162965, 0.23340827, 0.86608513, 0.10651165, 0.25163994,
       0.55776127, 0.28246138, 0.52050514, 0.6223602 , 0.52624221,
       0.28571611, 0.87131256, 0.28808249, 0.55837679, 0.34376

In [4]:
sum(x)

50.808500431978906

In [5]:
np.sum(x)

50.80850043197893

In [7]:
arr = np.random.rand(10**7)

In [8]:
%timeit sum(arr)

1.15 s ± 58.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
%timeit np.sum(arr)

16.2 ms ± 831 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
np.min(x)

0.025645205770550072

In [11]:
np.max(x)

0.991456345375396

In [12]:
x.sum()

50.80850043197893

In [13]:
x.min()

0.025645205770550072

In [14]:
y = np.arange(16).reshape(4,4)

In [15]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.sum(y)

120

In [18]:
np.sum(y,axis=0)  #竖着求和

array([24, 28, 32, 36])

In [19]:
np.sum(y,axis=1)

array([ 6, 22, 38, 54])

In [20]:
np.prod(x)

5.234532877127596e-41

In [21]:
np.prod(y)

0

In [22]:
np.prod(y+1)

2004189184

In [23]:
np.prod(y+1,axis=1)

array([   24,  1680, 11880, 43680])

In [24]:
np.mean(x)

0.5080850043197893

In [25]:
np.mean(y)

7.5

In [26]:
np.mean(y,axis=0)

array([6., 7., 8., 9.])

In [27]:
np.median(y,axis=0)

array([6., 7., 8., 9.])

In [31]:
z = np.array([34324,34544,4343,5563,224353])

In [32]:
np.mean(z) # 均值

60625.4

In [33]:
np.median(z)  #中位数

34324.0

In [34]:
np.percentile(z,q=50)   #百分位数

34324.0

In [35]:
np.var(z)  #方差

6875661302.640001

In [38]:
np.sum((z-np.mean(z))**2)/np.size(z)  #每个值减去均值之后的平方求和除以数目

6875661302.640001

In [40]:
np.std(z)  #标准差

82919.60746795658

In [41]:
x = np.random.normal(0,1,size=1000000)

In [42]:
np.mean(x)

0.0005468168892882293

In [43]:
np.std(x)

0.9992679371529958