In [1]:
import numpy as np

## fancy indexing

In [2]:
x = np.array(list('ABCDEFG'))

In [4]:
x[2]

'C'

In [5]:
x[1:3]

array(['B', 'C'], dtype='<U1')

In [6]:
x[1:5:2]

array(['B', 'D'], dtype='<U1')

In [7]:
ind = [1,2,5]

In [9]:
x[ind]  #传递索引数组

array(['B', 'C', 'F'], dtype='<U1')

In [10]:
ind = np.arange(1,5).reshape(2,-1)

In [11]:
x[ind]

array([['B', 'C'],
       ['D', 'E']], dtype='<U1')

In [12]:
y = np.arange(16).reshape(4,4)

In [13]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
row = [0,1,3]
col = [2,3,1]

In [17]:
y[row,col]

array([ 2,  7, 13])

In [18]:
y[2,col]

array([10, 11,  9])

In [19]:
col = [True,False,True,True]
y[3,col]

array([12, 14, 15])

## 比较运算

In [20]:
x = np.arange(10)

In [21]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [22]:
x[x<5]

array([0, 1, 2, 3, 4])

In [23]:
x[x==5]

array([5])

In [24]:
x[x-1!=x//2]

array([0, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[x+2==x//2+3]

array([1, 2])

In [26]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
y[y<5]

array([0, 1, 2, 3, 4])

In [28]:
y[y<7]

array([0, 1, 2, 3, 4, 5, 6])

In [29]:
np.sum(y<8)

8

In [30]:
np.count_nonzero(x>4)

5

In [31]:
np.any(x<4)  #有一个符合就返回True

True

In [32]:
np.all(x>3)

False

In [33]:
np.all(x>=0)

True

In [34]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
y > 2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
np.sum(y%2==0)

8

In [36]:
np.sum(y%2==0,axis=0)

array([4, 0, 4, 0])

In [37]:
np.sum(y%2==0,axis=1)

array([2, 2, 2, 2])

In [43]:
np.sum((y > 2) & (y < 10))  #按位与

7

In [44]:
np.sum((y == 2) | (y == 10))  #按位或

2

In [46]:
np.sum(~(y == 2))   #取反

15

In [47]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
y[:,-1]

array([ 3,  7, 11, 15])

In [49]:
y[:,-1] % 3 == 0

array([ True, False, False,  True])

In [50]:
y[y[:,-1] % 3 == 0,:]   #取行的末尾能被3整除的行

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])