## argmin  argmax  argsort  argpartition  返回索引位置

In [2]:
import numpy as np

In [4]:
np.random.seed(2)
x = np.random.random(50)
x

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
       0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728,
       0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987,
       0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548,
       0.50524609, 0.0652865 , 0.42812233, 0.09653092, 0.12715997,
       0.59674531, 0.226012  , 0.10694568, 0.22030621, 0.34982629,
       0.46778748, 0.20174323, 0.64040673, 0.48306984, 0.50523672,
       0.38689265, 0.79363745, 0.58000418, 0.1622986 , 0.70075235,
       0.96455108, 0.50000836, 0.88952006, 0.34161365, 0.56714413,
       0.42754596, 0.43674726, 0.77655918, 0.53560417, 0.95374223])

In [5]:
np.min(x)

0.025926231827891333

In [6]:
np.argmin(x)

1

In [7]:
x[4]

0.42036780208748903

In [8]:
np.argmax(x)

40

In [9]:
x[40]

0.9645510800892552

In [10]:
ind = np.argwhere(x>0.5)

In [11]:
ind

array([[ 2],
       [ 7],
       [10],
       [11],
       [13],
       [15],
       [16],
       [18],
       [20],
       [25],
       [32],
       [34],
       [36],
       [37],
       [39],
       [40],
       [41],
       [42],
       [44],
       [47],
       [48],
       [49]], dtype=int32)

In [12]:
x[ind]

array([[0.54966248],
       [0.61927097],
       [0.62113383],
       [0.52914209],
       [0.51357812],
       [0.78533515],
       [0.85397529],
       [0.84656149],
       [0.50524609],
       [0.59674531],
       [0.64040673],
       [0.50523672],
       [0.79363745],
       [0.58000418],
       [0.70075235],
       [0.96455108],
       [0.50000836],
       [0.88952006],
       [0.56714413],
       [0.77655918],
       [0.53560417],
       [0.95374223]])

In [13]:
x = np.arange(10)

In [14]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.random.shuffle(x)  #打乱x

In [16]:
x

array([8, 9, 5, 7, 4, 1, 2, 0, 3, 6])

In [17]:
np.sort(x)   #排序x，x不会变

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x

array([8, 9, 5, 7, 4, 1, 2, 0, 3, 6])

In [21]:
ind = np.argsort(x)   #返回排序好之后的索引
ind

array([7, 5, 6, 8, 4, 2, 9, 3, 0, 1], dtype=int32)

In [23]:
x[ind[:3]]  #去前面三个即最小的三个

array([0, 1, 2])

In [24]:
x[ind[-3:]]   #取后面三个即最大的三个

array([7, 8, 9])

In [25]:
x

array([8, 9, 5, 7, 4, 1, 2, 0, 3, 6])

In [26]:
np.partition(x,4)  #小于4的在左面，大于4的在右面

array([0, 1, 2, 3, 4, 5, 6, 9, 7, 8])

In [28]:
np.argpartition(x,4)  #返回索引值

array([7, 5, 6, 8, 4, 2, 9, 1, 3, 0], dtype=int32)

In [29]:
y = np.random.randint(20,size=(4,5))

In [30]:
y

array([[ 6,  5,  1, 18, 11],
       [ 5, 10,  8,  3,  0],
       [16, 11, 16,  8,  6],
       [10,  5, 17, 15, 13]])

In [31]:
np.sort(y)

array([[ 1,  5,  6, 11, 18],
       [ 0,  3,  5,  8, 10],
       [ 6,  8, 11, 16, 16],
       [ 5, 10, 13, 15, 17]])

In [32]:
np.sort(y,axis=0)

array([[ 5,  5,  1,  3,  0],
       [ 6,  5,  8,  8,  6],
       [10, 10, 16, 15, 11],
       [16, 11, 17, 18, 13]])

In [34]:
np.argsort(y,axis=0)

array([[1, 0, 0, 1, 1],
       [0, 3, 1, 2, 2],
       [3, 1, 2, 3, 0],
       [2, 2, 3, 0, 3]], dtype=int32)