In [1]:
import numpy as np

## ndim shape size

In [4]:
a = np.arange(10)

In [5]:
a.size

10

In [8]:
a.ndim  #查看是几维的

1

In [9]:
a.shape   

(10,)

In [10]:
A = np.ones(shape=(3,5))

In [11]:
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
A.ndim

2

In [13]:
A.size

15

In [14]:
A.shape

(3, 5)

In [15]:
x = np.array([[2,4,5],
             [3,5,2,3]])

In [16]:
x.size

2

In [17]:
x.shape

(2,)

In [18]:
x.ndim

1

In [19]:
x

array([list([2, 4, 5]), list([3, 5, 2, 3])], dtype=object)

## reshape 更改维度

In [22]:
n = np.arange(10)

In [25]:
n.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
n.reshape(2,-3)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
n.reshape(-4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 取值

In [31]:
y = np.arange(15).reshape(3,-3)

In [32]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
y[0]

array([0, 1, 2, 3, 4])

In [34]:
y[-1]

array([10, 11, 12, 13, 14])

In [35]:
y[0,1]  # y[0][1]   y[(0,1)]

1

## 切片

In [36]:
a = np.arange(10)

In [37]:
a[:4]

array([0, 1, 2, 3])

In [38]:
a[5:]

array([5, 6, 7, 8, 9])

In [40]:
a[0:8:2]

array([0, 2, 4, 6])

In [41]:
a[::3]

array([0, 3, 6, 9])

In [42]:
a[::-1]   # 也是倒叙操作，

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 二维数组切片操作

In [44]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
y[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [46]:
y[:2][:1]

array([[0, 1, 2, 3, 4]])

In [47]:
y[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [48]:
y[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

## numpy中的切片跟原来的矩阵有关系，python的list没有关系

In [52]:
z = y[:2,:2]

In [53]:
z[0,0]=88

In [54]:
y  #y的值跟着变了

array([[88,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
z1 = y[:2,:3].copy()   #脱离关系

In [56]:
z1[0,0]=99

In [57]:
z1

array([[99,  1,  2],
       [ 5,  6,  7]])

In [58]:
y

array([[88,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])