pip install numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.3'

In [3]:
li = list(range(10))
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
import array #array只能存放一种数据类型
arr = array.array('i',list(range(10)))  #第一个参数是数据类型
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[3]

3

In [7]:
arr[3] = 33

In [8]:
arr

array('i', [0, 1, 2, 33, 4, 5, 6, 7, 8, 9])

In [10]:
# arr[5] = 'a'     #TypeError: an integer is required (got type str)

## numpy.ndarray

In [13]:
nparr = np.array(list(range(10)))

In [14]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
type(nparr)

numpy.ndarray

In [16]:
nparr.dtype  #随着操作系统改变

dtype('int32')

In [17]:
nparr[3] = 33
nparr

array([ 0,  1,  2, 33,  4,  5,  6,  7,  8,  9])

In [19]:
# nparr[4] = 'a'  #ValueError: invalid literal for int() with base 10: 'a'

In [20]:
nparr[4] = 32.2
nparr

array([ 0,  1,  2, 33, 32,  5,  6,  7,  8,  9])

In [21]:
nparr2 = np.array([1,2,3.0])  #初始化有浮点数则都是浮点
nparr2

array([1., 2., 3.])

In [23]:
nparr2.dtype

dtype('float64')

In [24]:
nparr3 = np.array([1,2],dtype='float')   #初始化时dtype指定类型

In [25]:
nparr3

array([1., 2.])

In [30]:
def python_test(n):
    a = [i**2 for i in range(n)]
    b = [i**3 for i in range(n)]
    c = [a[i]+b[i] for i in range(len(a))]
    return c

In [31]:
python_test(10)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

In [34]:
def numpy_test(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

In [35]:
numpy_test(10)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810], dtype=int32)

In [36]:
%time res = python_test(1000000)

Wall time: 827 ms


In [37]:
%time res = python_test(10000000)

Wall time: 8.41 s


In [38]:
%time res = numpy_test(10000000)

Wall time: 150 ms
