In [1]:
import numpy as np

In [2]:
np.arange(4)

array([0, 1, 2, 3])

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.array(range(5,10,2))

array([5, 7, 9])

## numpy.arange    步长可以是小数

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3,33,4)

array([ 3,  7, 11, 15, 19, 23, 27, 31])

In [10]:
np.arange(3,33,4.8)   #步长可以是浮点数

array([ 3. ,  7.8, 12.6, 17.4, 22.2, 27. , 31.8])

## numpy.zeros  

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10,dtype='i')  # 等效于np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [14]:
np.zeros((3,5))    #传入元组得到矩阵

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros(dtype=int,shape=(4,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## np.ones

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones(dtype=int,shape=(2,3))

array([[1, 1, 1],
       [1, 1, 1]])

## np.full   填充相同任意数字

In [18]:
np.full(3,42)

array([42, 42, 42])

In [19]:
np.full((3,2),23)

array([[23, 23],
       [23, 23],
       [23, 23]])

In [22]:
np.full(shape=(3,4),fill_value=3.3)

array([[3.3, 3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3, 3.3]])

In [23]:
np.full(shape=(3,4),fill_value=3.3,dtype=int)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

## numpy.linspace(起始数，终止数，取点数）/包含终止数，平均取点

In [25]:
np.linspace(1,32,23)

array([ 1.        ,  2.40909091,  3.81818182,  5.22727273,  6.63636364,
        8.04545455,  9.45454545, 10.86363636, 12.27272727, 13.68181818,
       15.09090909, 16.5       , 17.90909091, 19.31818182, 20.72727273,
       22.13636364, 23.54545455, 24.95454545, 26.36363636, 27.77272727,
       29.18181818, 30.59090909, 32.        ])

In [26]:
np.linspace(1,33,17)   # 这个可以产生等差数，range也可以调整步长就行了

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33.])

In [27]:
np.linspace(0,20,10,endpoint=False)  #不包含终止数

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

## numpy.random

In [29]:
np.random.randint(1,5)

3

In [30]:
np.random.randint(1,6,2)  # 最后一个参数指定产生几个随机数

array([3, 5])

In [31]:
np.random.randint(1,6,size=4)

array([2, 1, 5, 5])

In [32]:
np.random.randint(1,6,size=(3,4))

array([[5, 2, 1, 3],
       [2, 1, 4, 2],
       [5, 2, 5, 1]])

In [38]:
np.random.seed(100)   #随机数种子确定后面的随机数不会变
np.random.randint(1,43,2)

array([ 9, 25])

In [40]:
np.random.randint(1,21,3)

array([17, 11,  3])

In [42]:
np.random.random()   #产生0-1之间的均匀随机数

0.21010774244258368

In [43]:
np.random.random(5)   

array([0.4527399 , 0.87014264, 0.06368104, 0.62431189, 0.52334774])

In [44]:
np.random.random((3,4))   

array([[0.56229626, 0.00581719, 0.30742321, 0.95018431],
       [0.12665424, 0.07898787, 0.31135313, 0.63238359],
       [0.69935892, 0.64196495, 0.92002378, 0.29887635]])

In [45]:
np.random.normal(size=4)  #均值为0，标准差为1，符合正态分布的随机数

array([-1.26691058,  0.27100509,  2.14076322,  0.47536904])

In [47]:
np.random.normal(size=(3,5))

array([[ 0.24652489, -1.08417396, -2.3815826 , -0.4363488 , -2.07241186],
       [-1.29543984, -0.46402358, -0.05702664,  0.27592974,  1.49451522],
       [ 0.56682064, -2.30337426,  1.37700072, -1.18738682,  0.07939305]])