In [1]:
import numpy as np

In [2]:
np.random.seed(1)
x = np.random.randint(1, 10, size=30)
x

array([6, 9, 6, 1, 1, 2, 8, 7, 3, 5, 6, 3, 5, 3, 5, 8, 8, 2, 8, 1, 7, 8,
       7, 2, 1, 2, 9, 9, 4, 9])

In [13]:
y = x.reshape(-1,3)   #将X处理为⼀个3列的矩阵

In [14]:
y

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3],
       [5, 3, 5],
       [8, 8, 2],
       [8, 1, 7],
       [8, 7, 2],
       [1, 2, 9],
       [9, 4, 9]])

In [21]:
y[y[:,-1]<=3][:,-1] = 0

In [22]:
y

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3],
       [5, 3, 5],
       [8, 8, 2],
       [8, 1, 7],
       [8, 7, 2],
       [1, 2, 9],
       [9, 4, 9]])

In [5]:
# 将第三列中，⼩于等于3的修改为0、⼤于3且⼩于等于6的修改为1、⼤于6的修改为2
li = []  #定义一个空列表用于存放修改后的值
for i in y[:,-1:]:
    if i <= 3:
        li.append(0)
    elif i > 3 and i <= 6:
        li.append(1)
    else:
        li.append(2)
y = np.hstack([y[:,:2],np.array(li).reshape(-1,1)])  #将y的前两列和li的（-1，1）维度合并

In [6]:
y  

array([[6, 9, 1],
       [1, 1, 0],
       [8, 7, 0],
       [5, 6, 0],
       [5, 3, 1],
       [8, 8, 0],
       [8, 1, 2],
       [8, 7, 0],
       [1, 2, 2],
       [9, 4, 2]])

In [7]:
#  分离出样本的特征和分类标记，分别存放在两个变量中，⽤ X_train 存放样本特征, y_train 存放分类标记
x_train,y_train = np.hsplit(y,[2])
x_train

array([[6, 9],
       [1, 1],
       [8, 7],
       [5, 6],
       [5, 3],
       [8, 8],
       [8, 1],
       [8, 7],
       [1, 2],
       [9, 4]])

In [8]:
y_train

array([[1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [2]])

In [9]:
# 分类为0的样本
y[y[:,-1]==0,:-1]

array([[1, 1],
       [8, 7],
       [5, 6],
       [8, 8],
       [8, 7]])

In [10]:
# 分类为1的样本
y[y[:,-1]==1,:-1]

array([[6, 9],
       [5, 3]])

In [11]:
# 分类为2的样本
y[y[:,-1]==2,:-1]

array([[8, 1],
       [1, 2],
       [9, 4]])