In [1]:
import numpy as np

In [4]:
x = np.array([[1.2,1.5,1.8],
             [1.3,1.4,1.9],
             [1.1,1.6,1.7]])
x

array([[1.2, 1.5, 1.8],
       [1.3, 1.4, 1.9],
       [1.1, 1.6, 1.7]])

In [6]:
y = np.array([[5,10,9]]).T
y

array([[ 5],
       [10],
       [ 9]])

使⽤循环的⽅式计算每天的采购总⾦额

In [19]:
%%timeit
li = []  #采购总金额列表
for i in range(3):
    for j in x[i:i+1,:]:
        #a = y.T*j
        li.append(np.sum(y.T*j))
li

21.2 µs ± 189 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [20]:
li

[37.2, 37.599999999999994, 36.8]

使用矩阵的方式计算每天的采购总⾦额

In [18]:
%%timeit
lis = x.dot(y).T
lis  #采购总金额

1.16 µs ± 5.95 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [21]:
lis

array([[37.2, 37.6, 36.8]])

明显使用矩阵时间短些